version: '3.1'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    container_name: my_jenkins
    ports:
      - 8889:8080
      - 50000:50000
    volumes:
      - /usr/local/software/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always